apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-app
  template:
    metadata:
      labels:
        app: reddit-clone-app
    spec:
      containers:
        - name: reddit-clone-app
          image: shailaja97/reddit-clone-pipeline:1.0.0-16
          resources:
            limits:
              cpu: "200m"
              memory: "300Mi"
            requests:
              cpu: "100m"
              memory: "150Mi"
          ports:
            - containerPort: 3000
